export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const ADD_TO_TAGS_FILTER = "ADD_TO_TAGS_FILTER";
export const REMOVE_FROM_TAGS_FILTER = "REMOVE_FROM_TAGS_FILTER";
export const CHANGE_TYPE_FILTER = "CHANGE_TYPE_FILTER";
export const SEARCH_FILTER = "SEARCH_FILTER";
export const LOAD_SERVICES = "LOAD_SERVICES";
